global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']
  - job_name: 'canary-app'
    static_configs:
      - targets: ['host.docker.internal:8080']
