apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-app
spec:
  replicas: 2
  strategy:
    canary:
      steps:
      - setWeight: 20
      - setWeight: 50
      - setWeight: 100
