slo_targets:
  p99_ms: 50
  error_rate_pct: 0.5
lookback_minutes: 2
cooldown_minutes: 5
providers:
  prometheus:
    url: http://localhost:9090
    job: "canary-app"
  datadog:
    api_key: ${DD_API_KEY}
    app_key: ${DD_APP_KEY}
    site: "datadoghq.com"
dependencies: []
